### ISSUE TITLE
Would this work for connecting to networks with spaces in the SSID?

### ISSUE THREAD

**Issue by sgbaird** [george-hawkins/micropython-wifi-setup#4]
Wondering if I should try this out as a potential workaround or if I should just tell users they can't connect to networks that have spaces in the name (when connecting via Pico W).

**Comment by george-hawkins** [comment]
I'm not really sure what the original problem is that you're trying to work around. Have you seen the code in this repo fail for SSIDs with spaces in the name?

There's no good reason why it should. If it's doing so then it's a bug (though if that's the case, it doesn't mean I have time to fix it, but you're welcome to submit a PR).

**Comment by sgbaird** [comment]
@george-hawkins someone I was working with mentioned he and several others were unable to connect to networks with spaces in the names on the Pico W. Seems that in reality, the networks that had spaces were 5G, and the networks without spaces were 2.4 GHz, and only 2.4 GHz is supported on the board.
